In [43]:
import pandas as pd
import numpy as np

df = pd.read_csv("test.csv", sep=';')
df

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1110,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1111,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1112,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1113,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1114,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
# criando os datasets reduzidos
num_linhas = 1115


df_teste_redu = pd.DataFrame({
    'intensidade': [0 for i in range(num_linhas)],
    'simetria': [0 for i in range(num_linhas)],
    'label': [l for l in df['label']]
})

df_sem_label = df.loc[:, 'pixel0':'pixel783']

# intensidade
for linha in range(1115):
    i = 0
    for x in range(784):
        i+= df_sem_label[f'pixel{str(x)}'].loc[linha]
    i /= 255
    df_teste_redu['intensidade'].loc[linha] = i

In [45]:
df_teste_redu

      intensidade  simetria  label
0      147.933333         0      0
1      131.054902         0      0
2      134.890196         0      0
3      139.976471         0      0
4      129.580392         0      0
...           ...       ...    ...
1110    96.121569         0      5
1111    98.439216         0      5
1112    95.141176         0      5
1113   106.882353         0      5
1114   117.639216         0      5

[1115 rows x 3 columns]

In [61]:


# simetria vertical
svs = []
for linha in range(1115):
    sv = 0

    for i in range(28):
        Pv = 0
        for j in range(14):
            pixel1 = i * 28 + j # i*28 Ã© para chegar atÃ© a linha i, j Ã© o que ele "anda" para chegar atÃ© a coluna j
            pixel2 = i * 27 + (28 - j) # i*28 Ã© para chegar atÃ© a linha i, j Ã© o que ele "anda" da direita pra esquerda para chegar atÃ© a coluna
            Pv += abs(df_sem_label.iloc[linha, pixel1+1] - df_sem_label.iloc[linha, pixel2+1])
    sv = Pv/255
    svs.append(sv)

# simetria horizontal
shs = []
for linha in range(1115):
    sh = 0

    for j in range(14):
        Ph = 0
        for i in range(28):
            pixel1 = i * 28 + j
            pixel2 = (27-i) * 28 + j
            Ph += abs(df_sem_label.iloc[linha, pixel1+1] - df_sem_label.iloc[linha, pixel2+1])
    sh = Ph/255
    shs.append(sh)


simetria_total = [v + h for v, h in zip(svs, shs)]

In [62]:
df_teste_redu['simetria']

0       0
1       0
2       0
3       0
4       0
       ..
1110    0
1111    0
1112    0
1113    0
1114    0
Name: simetria, Length: 1115, dtype: int64